version: '3'

services:
  raffle-bot:
    build: .
    container_name: raffle-bot
    restart: always
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - TZ=Europe/Moscow 